[package]
name = "noted"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/peanutbuttboi/noted"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.104"
crossterm = "0.29.0"
dirs = "7.0.0"
edit = "0.1.5"
ratatui = { version  = "0.30.2", features = ["unstable-rendered-line-info"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
toml = "1.1.6"
tui-markdown = "0.3.9"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"

[dev-dependencies]
tempfile = "3.27.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
